spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mall?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: 1q2w3e4r!!

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  port: 8080

  mail:
    host: smtp.naver.com
    username: amy9047@naver.com
    password: 1q2w3e4r!!
    port: 465
    properties:
      mail:
        transport:
          protocol: smtp
        smtp:
          auth: true
          starttls:
            enable: true
          debug: true
          ssl:
            trust: smtp.naver.com
            enable: true

